### PR TITLE
Adding OAuth, cleaning up

### PR DESCRIPTION
**Pull request by leesdolphin**
Added OAuth and cleaned the front page.
Allowed [direct linking](https://leesdolphin.github.io/js-hatrack/#repo=LABHR/octohatrack) to a repositories hat rack, and assuming that the user is authenticated it will start loading the moment the DOM is ready.

The current flow for direct linking is:
 1. The user visits the link.
 2. If the user is logged in using OAuth and we have the credentials cached then:
   - Load the contributors immediately.
 3. Otherwise pre-fill the repository field and allow the user to select `Login with GitHub` or fill in their username and token.

Also explicitly removed the option of a password(though it will still work because token auth uses the same mechanism as password auth) because I don't feel comfortable encouraging or even presenting the option of entering the GitHub password on another site.

### CODE REVIEW

**Comment by glasnt** [comment]
This is absolutely fantastic! Thank you so much for all your efforts!

A few things I've noticed:
 - Using the GitHub login option returns duplicate entries
 - Using the oauth token login (which allows no token) returns a single set of entries

Important changes: 
 - it should not allow for an oauth token. It should only accept github oauth. The only form should be the 'enter github repo' name

What I'd like: 
 - a option to sign out if you're signed in
 - the main page has a blurb about what this app does (I'll write something up)
 - the main entrypoint only gives the option of github oauth only
 - can people using the permalink be oauth checked on reentry?

Possibly before this is 'live', I'd rename this repo to something else. Given the namespace, it'd be 'labhr.github.io/something'. I'm leaning towwards renaming it to 'github' to match the stackoverflow and wikipedia endpoints

**Comment by leesdolphin** [comment]
So I've done a bit more work on it. I've removed the user/token form, and I've added a sign-out button. I've fixed up the way locations are handled so that it no longer refreshes when you want to return.

I don't fully understand your last point about 'oauth checked on reentry'. The way the page works is that it will try and use the locally cached keys to authenticate. If those keys are missing(the user is unauthenticated) then it will show the form with the text box pre-filled.

I'm a little hesitant about the sign out option too. Right now it clears the local cache, but does not de-authenticate the user from the app. I don't know if that is intended functionality.

Any comments are greatly appreciated.

**Comment by glasnt** [comment]
> So I've done a bit more work on it. I've removed the user/token form, and I've added a sign-out button. I've fixed up the way locations are handled so that it no longer refreshes when you want to return.

This is looking freaking fancy! Well done! :clap: 

> I don't fully understand your last point about 'oauth checked on reentry'. The way the page works is that it will try and use the locally cached keys to authenticate. If those keys are missing(the user is unauthenticated) then it will show the form with the text box pre-filled.

This is me trying to get the full 'user experience' of 'i sign into a thing, i sign out again'. Something like what https://github.com/notwaldorf/frankly seems to do (even if it's faked out)

> I'm a little hesitant about the sign out option too. Right now it clears the local cache, but does not de-authenticate the user from the app. I don't know if that is intended functionality.

Deauthentication iirc is service side (as in, I have to log into github to remove the app from my list of apps.

**Comment by leesdolphin** [comment]
I'm happy with this to go out if you are.

**Comment by glasnt** [comment]
@leesdolphin :shipit:

**Comment by leesdolphin** [comment]
Oh ... one more thing, we should change the OAuth App from the testing one to a 'real' one

**Comment by glasnt** [comment]
Oh yes. Do you have the rights to do that?

**Comment by leesdolphin** [comment]
Ok, I've just transferred it to LABHR.

**Comment by glasnt** [comment]
@leesdolphin I've clicked the button

**Pull request merged**
